### ISSUE TITLE
vue-code-view@0.4.1+vue@2.6 无法预览，提示错误TypeError:Assignment to constant variable 

### ISSUE THREAD

**Issue by Lxl95** [andurils/vue-code-view#44]
TypeError: Assignment to constant variable 
at eval (eval at genComponent (output-container.vue:2:1) 
at VueComponent.genComponent (output-container.vue:78:1)

打包生成的文件vue-code-viewer.common也报这个错误

**Comment by Lxl95** [comment]
已解决，src\code-viewer\output-container.vue  const componentScript = {}; 改成 let componentScript = {};
